# Change baseurl before deploy
baseurl = "https://anthropeneur.com"
languageCode = "en-us"
title = "The Anthropeneur"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[params]
utterancesRepo = "Michele-Minervini/anthropeneur.com"

[pagination]
pagerSize = 5